### PR TITLE
my first attempt to solidity with the support of ChatGPT, I hope that…

### PR DESCRIPTION
**Pull request by rjpartingtoniii**
… this is helpful in some way

### CODE REVIEW

**Comment by vzotova** [comment]
Congrats on first attempt!
Couple things that necessary to make it work:
* project structure, default hardhat project for example
* some simple test to just have understanding how it should work
Regarding contract code itself: 
* I suppose this project will utilize ERC721 NFT contract instead of ERC20 (or not?)
* Variables that goes through constructor better make immutable if they would not be changed later

**Comment by rjpartingtoniii** [comment]
Vicki, hi, thank you for your reply. As you know this is all new to me so I have a few clarifying questions.

When you say "hardhat project", what do you mean?

And when you say, "constructor", would you mind explaining what that means?

Lastly, what do you see his next steps in working on this contract?

**Comment by vzotova** [comment]
Hardhat project -> https://hardhat.org/hardhat-runner/docs/getting-started#quick-start
Constructor -> https://hardhat.org/hardhat-runner/docs/getting-started#quick-start
next step - project that can be compiled and run very very simple test

**Comment by rjpartingtoniii** [comment]
@vzotova, thank you so much for all of this. Will look into it and get back to you.

**Pull request merged**
